# Generated by Django 4.1.3 on 2022-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
