# Generated by Django 4.1.3 on 2022-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.BooleanField(),
        ),
    ]
